#!/usr/bin/env python3
"""Synthetic tamper fixtures for the Search V8 provenance verifier."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import stat
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import generate_provenance
import provenance_common
import verify_provenance
from provenance_common import (
    ARCHIVE_HEADER,
    BUNDLE_POLICY,
    CARGO_LOCK_POLICY,
    CRATES_IO_SOURCE,
    DEPENDENCY_DOMAIN,
    DEPENDENCY_HEADER,
    DEPENDENCY_MANIFEST_NAME,
    PACKAGE_DOMAIN,
    PROVENANCE_KEYS,
    PROVENANCE_DOMAIN,
    PROVENANCE_NAME,
    REGISTRY_ARCHIVES_NAME,
    SEARCH_LOCK_PATH,
    SEARCH_ROOT_DIRECTORY,
    SEARCH_ROOT_MANIFEST_ROLE,
    SEARCH_ROOT_NAME,
    SEARCH_ROOT_SOURCE,
    SEARCH_ROOT_VERSION,
    SOURCE_HEADER,
    SOURCE_DOMAIN,
    SOURCE_SNAPSHOT_NAME,
    ProvenanceError,
    bind_lock_packages,
    domain_hash,
    domain_preimage,
    package_key,
    parse_archives,
    parse_cargo_lock,
    parse_dependencies,
    provenance_identity,
    registry_archive_role,
    registry_manifest_role,
    search_root_key,
    valid_encoded_path,
)


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def table(header: list[str], rows: list[list[str]]) -> bytes:
    return (
        "\n".join(["\t".join(header), *("\t".join(row) for row in rows)]) + "\n"
    ).encode("ascii")


def cargo_lock(
    checksum: str,
    *,
    include_registry: bool = True,
    version: str = "4",
) -> bytes:
    registry = (
        f"""

[[package]]
name = "sha2"
version = "0.10.9"
source = "{CRATES_IO_SOURCE}"
checksum = "{checksum}"
"""
        if include_registry
        else ""
    )
    return f"""# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = {version}

[[package]]
name = "{SEARCH_ROOT_NAME}"
version = "{SEARCH_ROOT_VERSION}"
dependencies = [
 "sha2",
]
{registry}""".encode("ascii")


class ProvenanceVerifierTests(unittest.TestCase):
    def setUp(self) -> None:
        physical_temporary_root = Path(tempfile.gettempdir()).resolve(strict=True)
        self.temporary = tempfile.TemporaryDirectory(dir=physical_temporary_root)
        self.root = Path(self.temporary.name)
        self.commit = "1" * 40
        self.tree = "2" * 40
        self.git_tool_sha256 = "7" * 64
        self.archive_bytes = b"fixture crate archive bytes\n"
        self.checksum = digest(self.archive_bytes)
        self.archive = self.root / "sha2-0.10.9.crate"
        self.archive.write_bytes(self.archive_bytes)
        self.lock = self.root / "Cargo.lock.input"
        self.lock.write_bytes(cargo_lock(self.checksum))
        self.source = self.root / "source.tsv"
        self.source.write_bytes(self.source_bytes_for_lock(self.lock.read_bytes()))

        self.registry_key = package_key("sha2", "0.10.9", CRATES_IO_SOURCE)
        self.dependencies = self.root / "dependencies.tsv"
        self.dependencies.write_bytes(self.dependency_bytes())
        self.archives = self.root / "archives.tsv"
        self.archives.write_bytes(self.archive_manifest_bytes())
        self.bundle = self.root / "bundle"
        self.identity = generate_provenance.generate(
            self.generator_options(output=self.bundle)
        )
        self.reviewer = self.root / "independent-reviewer"
        self.reviewer.mkdir(mode=0o700)
        self.review_source = self.reviewer / SOURCE_SNAPSHOT_NAME
        self.review_lock = self.reviewer / "Cargo.lock"
        self.review_dependencies = self.reviewer / DEPENDENCY_MANIFEST_NAME
        self.review_archives = self.reviewer / REGISTRY_ARCHIVES_NAME
        shutil.copyfile(self.source, self.review_source)
        shutil.copyfile(self.lock, self.review_lock)
        shutil.copyfile(self.dependencies, self.review_dependencies)
        shutil.copyfile(self.archives, self.review_archives)

    def tearDown(self) -> None:
        for parent, directories, files in os.walk(self.root, topdown=False):
            for name in files:
                Path(parent, name).chmod(0o600)
            for name in directories:
                Path(parent, name).chmod(0o700)
        self.temporary.cleanup()

    def source_bytes_for_lock(
        self, lock_bytes: bytes, lock_path: str = SEARCH_LOCK_PATH
    ) -> bytes:
        rows = [
            [
                "1",
                "100644",
                "3" * 40,
                str(len(lock_bytes)),
                digest(lock_bytes),
                lock_path,
            ],
            [
                "2",
                "100644",
                "4" * 40,
                "12",
                "5" * 64,
                SEARCH_ROOT_MANIFEST_ROLE.removeprefix("repo:"),
            ],
        ]
        rows.sort(key=lambda row: row[-1].encode("ascii"))
        return table(
            SOURCE_HEADER,
            [[str(index), *row[1:]] for index, row in enumerate(rows, 1)],
        )

    def dependency_bytes(
        self,
        *,
        root_source: str = SEARCH_ROOT_SOURCE,
        root_manifest: str = SEARCH_ROOT_MANIFEST_ROLE,
        registry_checksum: str | None = None,
    ) -> bytes:
        checksum = registry_checksum or self.checksum
        root_key = package_key(SEARCH_ROOT_NAME, SEARCH_ROOT_VERSION, root_source)
        rows = [
            [
                root_key,
                SEARCH_ROOT_NAME,
                SEARCH_ROOT_VERSION,
                "path",
                root_source,
                root_manifest,
                self.tree,
                "none",
                "bin,custom-build",
                "none",
                f"sha2|build|all|{self.registry_key}",
            ],
            [
                self.registry_key,
                "sha2",
                "0.10.9",
                "registry",
                CRATES_IO_SOURCE,
                registry_manifest_role(self.registry_key),
                "none",
                checksum,
                "lib",
                "default",
                "none",
            ],
        ]
        rows.sort(key=lambda row: row[0])
        return table(
            DEPENDENCY_HEADER,
            [[str(index), *row] for index, row in enumerate(rows, 1)],
        )

    def archive_manifest_bytes(
        self,
        *,
        checksum: str | None = None,
        role: str | None = None,
    ) -> bytes:
        checksum = checksum or self.checksum
        return table(
            ARCHIVE_HEADER,
            [
                [
                    "1",
                    self.registry_key,
                    "sha2",
                    "0.10.9",
                    CRATES_IO_SOURCE,
                    checksum,
                    str(len(self.archive_bytes)),
                    checksum,
                    role or registry_archive_role(self.registry_key),
                ]
            ],
        )

    def generator_options(
        self,
        *,
        output: Path,
        source: Path | None = None,
        lock: Path | None = None,
        dependencies: Path | None = None,
        archives: Path | None = None,
        archive: Path | None = None,
        archive_key: str | None = None,
    ) -> argparse.Namespace:
        return argparse.Namespace(
            expected_commit=self.commit,
            expected_tree=self.tree,
            snapshot_git_tool_sha256=self.git_tool_sha256,
            source_snapshot=source or self.source,
            cargo_lock=lock or self.lock,
            dependency_manifest=dependencies or self.dependencies,
            registry_archives=archives or self.archives,
            registry_archive=[
                f"{archive_key or self.registry_key}={archive or self.archive}"
            ],
            target="aarch64-apple-darwin",
            profile="release",
            output=output,
        )

    def verifier_options(
        self,
        bundle: Path | None = None,
        *,
        archive: Path | None = None,
    ) -> argparse.Namespace:
        return argparse.Namespace(
            bundle=bundle or self.bundle,
            expected_commit=self.commit,
            expected_tree=self.tree,
            expected_provenance_sha256=self.identity,
            expected_snapshot_git_tool_sha256=self.git_tool_sha256,
            rederived_source_snapshot=self.review_source,
            rederived_cargo_lock=self.review_lock,
            rederived_dependency_manifest=self.review_dependencies,
            rederived_registry_archives=self.review_archives,
            registry_archive=[
                f"{self.registry_key}={archive or self.archive}"
            ],
        )

    def copied_bundle(self, name: str) -> Path:
        destination = self.root / name
        shutil.copytree(self.bundle, destination)
        return destination

    @staticmethod
    def replace(path: Path, old: str, new: str) -> None:
        path.chmod(0o600)
        text = path.read_text(encoding="ascii")
        if old not in text:
            raise AssertionError(f"missing fixture token {old!r}")
        path.write_text(text.replace(old, new, 1), encoding="ascii")
        path.chmod(0o400)

    def test_valid_bundle_round_trips_and_is_permission_sealed(self) -> None:
        self.assertEqual(
            verify_provenance.verify(self.verifier_options()), self.identity
        )
        self.assertEqual(stat.S_IMODE(self.bundle.stat().st_mode), 0o500)
        self.assertEqual(
            {path.name for path in self.bundle.iterdir()},
            {
                "Cargo.lock",
                "dependency-manifest.tsv",
                "registry-archives.tsv",
                "source-provenance.tsv",
                "source-snapshot.tsv",
            },
        )
        for path in self.bundle.iterdir():
            info = path.stat()
            self.assertTrue(stat.S_ISREG(info.st_mode))
            self.assertEqual(info.st_nlink, 1)
            self.assertEqual(stat.S_IMODE(info.st_mode), 0o400)

    def test_receipt_tree_tamper_is_rejected(self) -> None:
        bundle = self.copied_bundle("tree-tamper")
        self.replace(
            bundle / PROVENANCE_NAME,
            f"subject_tree\t{self.tree}",
            f"subject_tree\t{'f' * 40}",
        )
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(bundle))

    def test_dependency_edge_tamper_is_rejected(self) -> None:
        bundle = self.copied_bundle("edge-tamper")
        self.replace(
            bundle / DEPENDENCY_MANIFEST_NAME,
            "|build|all|",
            "|normal|all|",
        )
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(bundle))

    def test_independent_rederivation_mismatch_is_rejected(self) -> None:
        self.review_dependencies.write_bytes(
            self.review_dependencies.read_bytes() + b"\n"
        )
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options())

    def test_extra_bundle_role_is_rejected(self) -> None:
        bundle = self.copied_bundle("inventory-tamper")
        bundle.chmod(0o700)
        (bundle / "extra").write_text("extra\n", encoding="ascii")
        bundle.chmod(0o500)
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(bundle))

    def test_bundle_role_mode_and_symlink_are_rejected(self) -> None:
        bundle = self.copied_bundle("mode-tamper")
        (bundle / PROVENANCE_NAME).chmod(0o600)
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(bundle))

        bundle = self.copied_bundle("symlink-role-tamper")
        bundle.chmod(0o700)
        role = bundle / SOURCE_SNAPSHOT_NAME
        role.unlink()
        role.symlink_to(self.source)
        bundle.chmod(0o500)
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(bundle))

    def test_external_identity_and_git_tool_pins_are_required(self) -> None:
        options = self.verifier_options()
        options.expected_provenance_sha256 = "8" * 64
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(options)
        options = self.verifier_options()
        options.expected_snapshot_git_tool_sha256 = "8" * 64
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(options)

    def test_lock_v4_is_required(self) -> None:
        lock = self.root / "Cargo.lock.v3"
        lock_bytes = cargo_lock(self.checksum, version="3")
        lock.write_bytes(lock_bytes)
        source = self.root / "source-v3.tsv"
        source.write_bytes(self.source_bytes_for_lock(lock_bytes))
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "lock-v3-bundle",
                    source=source,
                    lock=lock,
                )
            )

    def test_lock_rejects_nonregistry_remote_sources(self) -> None:
        lock = self.root / "Cargo.lock.git-source"
        lock_bytes = f"""# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "{SEARCH_ROOT_NAME}"
version = "{SEARCH_ROOT_VERSION}"

[[package]]
name = "remote"
version = "0.1.0"
source = "git+https://example.invalid/repository"
""".encode("ascii")
        lock.write_bytes(lock_bytes)
        source = self.root / "source-git-lock.tsv"
        source.write_bytes(self.source_bytes_for_lock(lock_bytes))
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "git-lock-bundle",
                    source=source,
                    lock=lock,
                )
            )

    def test_selected_registry_package_must_exist_in_lock(self) -> None:
        lock = self.root / "Cargo.lock.no-registry"
        lock_bytes = cargo_lock(self.checksum, include_registry=False)
        lock.write_bytes(lock_bytes)
        source = self.root / "source-no-registry.tsv"
        source.write_bytes(self.source_bytes_for_lock(lock_bytes))
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "no-registry-bundle",
                    source=source,
                    lock=lock,
                )
            )

    def test_coordinated_manifest_checksum_tamper_still_loses_to_lock(self) -> None:
        wrong = "8" * 64
        dependencies = self.root / "dependencies-wrong-checksum.tsv"
        dependencies.write_bytes(self.dependency_bytes(registry_checksum=wrong))
        archives = self.root / "archives-wrong-checksum.tsv"
        archives.write_bytes(self.archive_manifest_bytes(checksum=wrong))
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "checksum-tamper-bundle",
                    dependencies=dependencies,
                    archives=archives,
                )
            )

    def test_coordinated_sidecar_rewire_loses_to_exact_lock_graph(self) -> None:
        other_bytes = b"unrelated but valid registry archive\n"
        other_checksum = digest(other_bytes)
        other_key = package_key("other", "1.0.0", CRATES_IO_SOURCE)
        other_archive = self.root / "other-1.0.0.crate"
        other_archive.write_bytes(other_bytes)
        lock_bytes = f"""# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "{SEARCH_ROOT_NAME}"
version = "{SEARCH_ROOT_VERSION}"
dependencies = [
 "sha2",
]

[[package]]
name = "other"
version = "1.0.0"
source = "{CRATES_IO_SOURCE}"
checksum = "{other_checksum}"

[[package]]
name = "sha2"
version = "0.10.9"
source = "{CRATES_IO_SOURCE}"
checksum = "{self.checksum}"
""".encode("ascii")
        lock = self.root / "Cargo.lock-rewired"
        lock.write_bytes(lock_bytes)
        source = self.root / "source-rewired.tsv"
        source.write_bytes(self.source_bytes_for_lock(lock_bytes))
        rows = [
            [
                search_root_key(),
                SEARCH_ROOT_NAME,
                SEARCH_ROOT_VERSION,
                "path",
                SEARCH_ROOT_SOURCE,
                SEARCH_ROOT_MANIFEST_ROLE,
                self.tree,
                "none",
                "bin,custom-build",
                "none",
                f"other|normal|all|{other_key}",
            ],
            [
                other_key,
                "other",
                "1.0.0",
                "registry",
                CRATES_IO_SOURCE,
                registry_manifest_role(other_key),
                "none",
                other_checksum,
                "lib",
                "default",
                "none",
            ],
        ]
        rows.sort(key=lambda row: row[0])
        dependencies = self.root / "dependencies-rewired.tsv"
        dependencies.write_bytes(
            table(
                DEPENDENCY_HEADER,
                [[str(index), *row] for index, row in enumerate(rows, 1)],
            )
        )
        archives = self.root / "archives-rewired.tsv"
        archives.write_bytes(
            table(
                ARCHIVE_HEADER,
                [
                    [
                        "1",
                        other_key,
                        "other",
                        "1.0.0",
                        CRATES_IO_SOURCE,
                        other_checksum,
                        str(len(other_bytes)),
                        other_checksum,
                        registry_archive_role(other_key),
                    ]
                ],
            )
        )
        with self.assertRaisesRegex(
            ProvenanceError,
            "dependency manifest edge is absent from the exact Cargo.lock graph",
        ):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "rewired-bundle",
                    source=source,
                    lock=lock,
                    dependencies=dependencies,
                    archives=archives,
                    archive=other_archive,
                    archive_key=other_key,
                )
            )

    def test_lock_graph_policy_is_closed_to_bare_unique_names(self) -> None:
        qualified = cargo_lock(self.checksum).replace(
            b' "sha2",\n', b' "sha2 0.10.9",\n'
        )
        with self.assertRaises(ProvenanceError):
            parse_cargo_lock(qualified)

        duplicate = cargo_lock(self.checksum) + f"""
[[package]]
name = "sha2"
version = "0.11.0"
source = "{CRATES_IO_SOURCE}"
checksum = "{'8' * 64}"
""".encode("ascii")
        with self.assertRaises(ProvenanceError):
            parse_cargo_lock(duplicate)

    def test_path_packages_must_map_unambiguously_into_lock(self) -> None:
        duplicate_source = "path:repo:research/aot/duplicate-search-root"
        duplicate_key = package_key(
            SEARCH_ROOT_NAME, SEARCH_ROOT_VERSION, duplicate_source
        )
        rows = [
            [
                search_root_key(),
                SEARCH_ROOT_NAME,
                SEARCH_ROOT_VERSION,
                "path",
                SEARCH_ROOT_SOURCE,
                SEARCH_ROOT_MANIFEST_ROLE,
                self.tree,
                "none",
                "bin,custom-build",
                "none",
                (
                    f"duplicate|normal|all|{duplicate_key};"
                    f"sha2|build|all|{self.registry_key}"
                ),
            ],
            [
                duplicate_key,
                SEARCH_ROOT_NAME,
                SEARCH_ROOT_VERSION,
                "path",
                duplicate_source,
                "repo:research/aot/duplicate-search-root/Cargo.toml",
                "9" * 40,
                "none",
                "lib",
                "none",
                "none",
            ],
            [
                self.registry_key,
                "sha2",
                "0.10.9",
                "registry",
                CRATES_IO_SOURCE,
                registry_manifest_role(self.registry_key),
                "none",
                self.checksum,
                "lib",
                "default",
                "none",
            ],
        ]
        rows.sort(key=lambda row: row[0])
        dependency_bytes = table(
            DEPENDENCY_HEADER,
            [[str(index), *row] for index, row in enumerate(rows, 1)],
        )
        _, dependencies, _, _, _ = parse_dependencies(dependency_bytes)
        lock_packages, _ = parse_cargo_lock(self.lock.read_bytes())
        with self.assertRaises(ProvenanceError):
            bind_lock_packages(lock_packages, dependencies)

    def test_real_archive_is_required_and_byte_authenticated(self) -> None:
        options = self.verifier_options()
        options.registry_archive = []
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(options)
        self.archive.write_bytes(b"different archive bytes\n")
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options())

    def test_symlink_archive_and_rederived_sidecar_are_rejected(self) -> None:
        archive_link = self.root / "archive-link.crate"
        archive_link.symlink_to(self.archive)
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(archive=archive_link))
        source_link = self.root / "source-link.tsv"
        source_link.symlink_to(self.source)
        options = self.verifier_options()
        options.rederived_source_snapshot = source_link
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(options)

    def test_rederived_sidecars_must_not_alias_retained_roles(self) -> None:
        fields_and_roles = [
            ("rederived_source_snapshot", SOURCE_SNAPSHOT_NAME),
            ("rederived_cargo_lock", "Cargo.lock"),
            ("rederived_dependency_manifest", DEPENDENCY_MANIFEST_NAME),
            ("rederived_registry_archives", REGISTRY_ARCHIVES_NAME),
        ]
        for field, role in fields_and_roles:
            options = self.verifier_options()
            setattr(options, field, self.bundle / role)
            with self.subTest(field=field), self.assertRaises(ProvenanceError):
                verify_provenance.verify(options)

    def test_hardlinked_archive_is_rejected(self) -> None:
        archive_link = self.root / "archive-hardlink.crate"
        os.link(self.archive, archive_link)
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(self.verifier_options(archive=archive_link))

    def test_hardlinked_rederived_sidecar_is_rejected(self) -> None:
        source_link = self.root / "source-hardlink.tsv"
        os.link(self.source, source_link)
        options = self.verifier_options()
        options.rederived_source_snapshot = source_link
        with self.assertRaises(ProvenanceError):
            verify_provenance.verify(options)

    def test_search_root_and_lock_roles_are_exact(self) -> None:
        other_directory = "research/aot/not-search-v8"
        dependencies = self.root / "other-root.tsv"
        dependencies.write_bytes(
            self.dependency_bytes(
                root_source=f"path:repo:{other_directory}",
                root_manifest=f"repo:{other_directory}/Cargo.toml",
            )
        )
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "other-root-bundle",
                    dependencies=dependencies,
                )
            )
        wrong_source = self.root / "wrong-lock-role.tsv"
        wrong_source.write_bytes(
            self.source_bytes_for_lock(self.lock.read_bytes(), "Cargo.lock")
        )
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(
                    output=self.root / "wrong-lock-role-bundle",
                    source=wrong_source,
                )
            )

    def test_output_must_be_one_new_physical_directory(self) -> None:
        existing = self.root / "existing-output"
        existing.mkdir()
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(output=existing)
            )
        linked = self.root / "linked-output"
        linked.symlink_to(existing, target_is_directory=True)
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(self.generator_options(output=linked))

        public_parent = self.root / "public-parent"
        public_parent.mkdir(mode=0o700)
        public_parent.chmod(0o777)
        with self.assertRaises(ProvenanceError):
            generate_provenance.generate(
                self.generator_options(output=public_parent / "bundle")
            )

    def test_absolute_output_parent_displacement_is_rejected(self) -> None:
        parent = self.root / "publication-parent"
        parent.mkdir(mode=0o700)
        displaced = self.root / "publication-parent-displaced"
        parent_info = parent.stat()
        parent_identity = (parent_info.st_dev, parent_info.st_ino)
        real_fsync = os.fsync
        moved = False

        def fsync_then_displace(descriptor: int) -> None:
            nonlocal moved
            real_fsync(descriptor)
            info = os.fstat(descriptor)
            if not moved and (info.st_dev, info.st_ino) == parent_identity:
                parent.rename(displaced)
                parent.mkdir(mode=0o700)
                moved = True

        with mock.patch.object(
            provenance_common.os, "fsync", side_effect=fsync_then_displace
        ), self.assertRaisesRegex(
            ProvenanceError,
            "absolute output parent changed before publication",
        ):
            generate_provenance.generate(
                self.generator_options(output=parent / "bundle")
            )
        self.assertTrue(moved)

    def test_length_framing_has_closed_known_answer_vectors(self) -> None:
        self.assertEqual(
            CARGO_LOCK_POLICY,
            "cargo-lock-v4-bare-unique-name-edges-v1",
        )
        self.assertEqual(
            BUNDLE_POLICY,
            "openat-nofollow-fstat-fsync-private-parent-absolute-rewalk-v3",
        )
        self.assertEqual(
            domain_hash(b"abc", []),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
        )
        domains = [
            (
                SOURCE_DOMAIN,
                b"FRE-SEARCH-V8-SOURCE-SNAPSHOT\0\x02",
            ),
            (
                DEPENDENCY_DOMAIN,
                b"FRE-SEARCH-V8-DEPENDENCY-CLOSURE\0\x02",
            ),
            (
                PROVENANCE_DOMAIN,
                b"FRE-SEARCH-V8-SOURCE-PROVENANCE\0\x02",
            ),
            (
                PACKAGE_DOMAIN,
                b"FRE-SEARCH-V8-PACKAGE-KEY\0\x02",
            ),
        ]
        for observed, expected in domains:
            self.assertEqual(observed, expected)
            self.assertEqual(domain_hash(observed, []), digest(expected))
        framed = (
            b"D"
            + (1).to_bytes(8, "little")
            + b"r"
            + (1).to_bytes(8, "little")
            + b"x"
        )
        self.assertEqual(domain_preimage(b"D", [("r", b"x")]), framed)
        boundary_a = domain_preimage(
            b"D", [("a", b"bc"), ("ab", b"c")]
        )
        boundary_b = domain_preimage(
            b"D", [("ab", b"c"), ("a", b"bc")]
        )
        self.assertNotEqual(boundary_a, boundary_b)

        provenance_rows = [
            (key, f"value-{index:02d}")
            for index, key in enumerate(PROVENANCE_KEYS[:-1])
        ]
        expected_provenance_preimage = bytearray(PROVENANCE_DOMAIN)
        for key, value in provenance_rows:
            key_bytes = key.encode("ascii")
            value_bytes = value.encode("ascii")
            expected_provenance_preimage.extend(
                len(key_bytes).to_bytes(8, "little")
            )
            expected_provenance_preimage.extend(key_bytes)
            expected_provenance_preimage.extend(
                len(value_bytes).to_bytes(8, "little")
            )
            expected_provenance_preimage.extend(value_bytes)
        pinned_provenance_digest = (
            "5d836aa66168278fab41180d636dfd4ef26a56c2289b6e04a5776a490c61a1a1"
        )
        self.assertNotIn(
            b"receipt-preimage", bytes(expected_provenance_preimage)
        )
        self.assertEqual(
            digest(bytes(expected_provenance_preimage)),
            pinned_provenance_digest,
        )
        self.assertEqual(
            provenance_identity(provenance_rows),
            pinned_provenance_digest,
        )
        expected_package_preimage = domain_preimage(
            PACKAGE_DOMAIN,
            [
                ("name", SEARCH_ROOT_NAME.encode("ascii")),
                ("version", SEARCH_ROOT_VERSION.encode("ascii")),
                ("source", SEARCH_ROOT_SOURCE.encode("ascii")),
            ],
        )
        self.assertEqual(search_root_key(), digest(expected_package_preimage))

    def test_absolute_and_nul_repository_locators_are_rejected(self) -> None:
        absolute_source = "path:repo:/private/tmp/root"
        absolute_key = package_key(
            SEARCH_ROOT_NAME, SEARCH_ROOT_VERSION, absolute_source
        )
        rows = [
            [
                "1",
                absolute_key,
                SEARCH_ROOT_NAME,
                SEARCH_ROOT_VERSION,
                "path",
                absolute_source,
                "repo:/private/tmp/root/Cargo.toml",
                self.tree,
                "none",
                "bin",
                "none",
                "none",
            ]
        ]
        with self.assertRaises(ProvenanceError):
            parse_dependencies(table(DEPENDENCY_HEADER, rows))
        with self.assertRaises(ProvenanceError):
            valid_encoded_path(f"{SEARCH_ROOT_DIRECTORY}/%00", "NUL path")

    def test_root_dependent_registry_locator_is_rejected(self) -> None:
        source = "registry+file:///private/tmp/index"
        key = package_key("registry-file", "0.1.0", source)
        rows = [
            [
                "1",
                key,
                "registry-file",
                "0.1.0",
                "registry",
                source,
                registry_manifest_role(key),
                "none",
                "8" * 64,
                "lib",
                "none",
                "none",
            ]
        ]
        with self.assertRaises(ProvenanceError):
            parse_dependencies(table(DEPENDENCY_HEADER, rows))

    def test_manifest_and_archive_roles_are_derived_and_unique(self) -> None:
        invalid_archive = self.archive_manifest_bytes(
            role="cargo-registry-archive:/private/tmp/sha2.crate"
        )
        with self.assertRaises(ProvenanceError):
            parse_archives(
                invalid_archive, {self.registry_key: self.checksum}
            )
        duplicate_source = "path:repo:crates/duplicate"
        first_key = package_key("first", "0.1.0", duplicate_source)
        second_key = package_key("second", "0.1.0", duplicate_source)
        rows = [
            [
                first_key,
                "first",
                "0.1.0",
                "path",
                duplicate_source,
                "repo:crates/duplicate/Cargo.toml",
                "3" * 40,
                "none",
                "lib",
                "none",
                "none",
            ],
            [
                second_key,
                "second",
                "0.1.0",
                "path",
                duplicate_source,
                "repo:crates/duplicate/Cargo.toml",
                "4" * 40,
                "none",
                "lib",
                "none",
                "none",
            ],
        ]
        rows.sort(key=lambda row: row[0])
        with self.assertRaises(ProvenanceError):
            parse_dependencies(
                table(
                    DEPENDENCY_HEADER,
                    [[str(index), *row] for index, row in enumerate(rows, 1)],
                )
            )


if __name__ == "__main__":
    unittest.main()
